#!/usr/bin/bash

OS=$(uname -o)

 if ! hash node &> /dev/null
 then
   printf "Nodejs not Installed :: Install it then run script again.\n"
   exit 1
 fi

 if [[ $1 == "install" ]]
 then
   if [[ $OS == *"Android"* ]]
   then
     cp -rf $(pwd)/system/termux/nvim $HOME/.config
     update-alternatives --config editor
     update-alternatives --config vi
   else
     cp -rf $(pwd)/system/linux/nvim $HOME/.config
     sudo update-alternatives --config editor
     sudo update-alternatives --config vi
   fi
 fi
